plugin: aws_ec2
regions:
  - us-east-1
keyed_groups:
  - key: tags.Name
    prefix: tag_Name_
  - key: instance_type
    prefix: instance_type_
hostnames:
  - ip-address
  - dns-name
  - tag:Name
compose:
  ansible_host: public_ip_address