---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install basic packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - python3-setuptools
    state: present

- name: Set timezone to UTC
  timezone:
    name: UTC

- name: Configure swapfile
  include_tasks: swap.yml